spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:sqlserver://localhost:1433;databaseName=effort_project
    username: sa
    password: root
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
mybatis:
  mapperLocations: classpath*:com/effort/mappers/*.xml
  typeAliasesPackage: com.effort.bean